.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. luckyblockcoin_qt test_luckyblockcoin_qt
clean: FORCE
	$(MAKE) -C .. luckyblockcoin_qt_clean test_luckyblockcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_luckyblockcoin_qt_check
luckyblockcoin-qt luckyblockcoin-qt.exe: FORCE
	 $(MAKE) -C .. luckyblockcoin_qt
